[phases.setup]
nixpkgs = ["python311", "pip"]

[phases.build]
cmds = [
    "nix-env -iA nixpkgs.python311 nixpkgs.pip",
    "pip install --upgrade pip",
    "pip install -r requirements.txt"
    ]

[start]
cmd = "gunicorn app.app:app"
