[phases.setup]
nixpkgs = ["python311", "pip"]

[phases.build]
cmds = [
    "echo 'Python version:' && python3 --version",
    "pip install --upgrade pip",
    "pip install -r requirements.txt"
    ]

[start]
cmd = "gunicorn app.app:app"
