"""3rd attempt

Revision ID: 911e0abd641c
Revises: 
Create Date: 2024-03-22 08:43:54.058249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '911e0abd641c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Users',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=345), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('user_name', sa.String(length=32), nullable=False),
    sa.Column('APIkey', sa.String(length=255), nullable=True),
    sa.Column('red', sa.String(length=50), nullable=True),
    sa.Column('blue', sa.String(length=50), nullable=True),
    sa.Column('green', sa.String(length=50), nullable=True),
    sa.Column('yellow', sa.String(length=50), nullable=True),
    sa.Column('token', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('token'),
    sa.UniqueConstraint('user_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Users')
    # ### end Alembic commands ###
